# 1.) Import the Credit Card Fraud Data From CCLE

In [2]:
## Nic Carpino Jan 27, 2023
#441B A3

In [3]:
import pandas as pd
from google.colab import drive
import matplotlib.pyplot as plt
import numpy as np

In [4]:
drive.mount('/content/gdrive/', force_remount = True)

Mounted at /content/gdrive/


In [5]:
df = pd.read_csv("/content/gdrive/MyDrive/Econ 441B/fraudTest.csv")

In [6]:
df.head()

Unnamed: 0 trans_date_trans_time            cc_num  \
0           0   2020-06-21 12:14:25  2291163933867244   
1           1   2020-06-21 12:14:33  3573030041201292   
2           2   2020-06-21 12:14:53  3598215285024754   
3           3   2020-06-21 12:15:15  3591919803438423   
4           4   2020-06-21 12:15:17  3526826139003047   

                               merchant        category    amt   first  \
0                 fraud_Kirlin and Sons   personal_care   2.86    Jeff   
1                  fraud_Sporer-Keebler   personal_care  29.84  Joanne   
2  fraud_Swaniawski, Nitzsche and Welch  health_fitness  41.28  Ashley   
3                     fraud_Haley Group        misc_pos  60.05   Brian   
4                 fraud_Johnston-Casper          travel   3.19  Nathan   

       last gender                       street  ...      lat      long  \
0   Elliott      M            351 Darlene Green  ...  33.9659  -80.9355   
1  Williams      F             3638 Marsh Union  ...  40.3207 -110.4360   
2     Lopez      F         9333 Valentine Point  ...  40.6729  -73.5365   
3  Williams      M  32941 Krystal Mill Apt. 552  ...  28.5697  -80.8191   
4    Massey      M     5783 Evan Roads Apt. 465  ...  44.2529  -85.0170   

   city_pop                     job         dob  \
0    333497     Mechanical engineer  1968-03-19   
1       302  Sales professional, IT  1990-01-17   
2     34496       Librarian, public  1970-10-21   
3     54767            Set designer  1987-07-25   
4      1126      Furniture designer  1955-07-06   

                          trans_num   unix_time  merch_lat  merch_long  \
0  2da90c7d74bd46a0caf3777415b3ebd3  1371816865  33.986391  -81.200714   
1  324cc204407e99f51b0d6ca0055005e7  1371816873  39.450498 -109.960431   
2  c81755dbbbea9d5c77f094348a7579be  1371816893  40.495810  -74.196111   
3  2159175b9efe66dc301f149d3d5abf8c  1371816915  28.812398  -80.883061   
4  57ff021bd3f328f8738bb535c302a31b  1371816917  44.959148  -85.884734   

   is_fraud  
0         0  
1         0  
2         0  
3         0  
4         0  

[5 rows x 23 columns]

# 2.) Select four columns to use as features (one just be trans_date_trans)

In [7]:
df_select = df[["trans_date_trans_time","category","amt","city_pop", "is_fraud"]]

In [8]:
df_select.head()

trans_date_trans_time        category    amt  city_pop  is_fraud
0   2020-06-21 12:14:25   personal_care   2.86    333497         0
1   2020-06-21 12:14:33   personal_care  29.84       302         0
2   2020-06-21 12:14:53  health_fitness  41.28     34496         0
3   2020-06-21 12:15:15        misc_pos  60.05     54767         0
4   2020-06-21 12:15:17          travel   3.19      1126         0

In [9]:
#df_select["time_var_BEFORE"] = df["trans_date_trans_time"]
#df_select["time_var_BEFORE"] = df["time_var_BEFORE"].str.replace "-"," ")

# 3.) Create a unique variable out of trans_date.

In [10]:
type(df["trans_date_trans_time"][0])

str

In [11]:
df_select["time_var_before"] = df_select["trans_date_trans_time"]

<ipython-input-11-703a95f2520d>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var_before"] = df_select["trans_date_trans_time"]


In [12]:
df_select["time_var_before"] = df_select["time_var_before"].str.replace("-","")

<ipython-input-12-984ac6afa394>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var_before"] = df_select["time_var_before"].str.replace("-","")


In [13]:
df_select["time_var_before"] = df_select["time_var_before"].str.replace(" ","")

<ipython-input-13-894274f43076>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var_before"] = df_select["time_var_before"].str.replace(" ","")


In [14]:
df_select["time_var_before"] = df_select["time_var_before"].str.replace(":","")

<ipython-input-14-c96ae07196b5>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var_before"] = df_select["time_var_before"].str.replace(":","")


In [15]:
df_select["time_var"] = np.nan

<ipython-input-15-35152e2b02ac>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select["time_var"] = np.nan


In [16]:
df_select['time_var_before'] = df_select['time_var_before'].astype('int')

<ipython-input-16-be1698bdb7b2>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['time_var_before'] = df_select['time_var_before'].astype('int')


In [17]:
df_select['time_var'] = np.where(df_select['time_var_before'] >= 20200631235959, 1, 0)
## looking at fraud midway through the year
## statiscially, more fraud occurs after July 1 due to seasonality travels (in the summer)

<ipython-input-17-2a4f88818315>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_select['time_var'] = np.where(df_select['time_var_before'] >= 20200631235959, 1, 0)


In [18]:
df_select

trans_date_trans_time        category     amt  city_pop  is_fraud  \
0        2020-06-21 12:14:25   personal_care    2.86    333497         0   
1        2020-06-21 12:14:33   personal_care   29.84       302         0   
2        2020-06-21 12:14:53  health_fitness   41.28     34496         0   
3        2020-06-21 12:15:15        misc_pos   60.05     54767         0   
4        2020-06-21 12:15:17          travel    3.19      1126         0   
...                      ...             ...     ...       ...       ...   
555714   2020-12-31 23:59:07  health_fitness   43.77       519         0   
555715   2020-12-31 23:59:09       kids_pets  111.84     28739         0   
555716   2020-12-31 23:59:15       kids_pets   86.88      3684         0   
555717   2020-12-31 23:59:24          travel    7.99       129         0   
555718   2020-12-31 23:59:34   entertainment   38.13    116001         0   

        time_var_before  time_var  
0        20200621121425         0  
1        20200621121433         0  
2        20200621121453         0  
3        20200621121515         0  
4        20200621121517         0  
...                 ...       ...  
555714   20201231235907         1  
555715   20201231235909         1  
555716   20201231235915         1  
555717   20201231235924         1  
555718   20201231235934         1  

[555719 rows x 7 columns]

In [19]:
#df["time_var_before"] = df["trans_date_trans_time"]

In [20]:
#df_select['time_var'] = np.where(df_select['trans_date_time_var'] == 0, 1, -1)

In [21]:
dummies = pd.get_dummies(df_select["category"])
X = pd.concat([dummies, df_select[["amt","city_pop", "time_var"]]], axis = 1) 
y = df_select["is_fraud"] 

In [22]:
X.head()

entertainment  food_dining  gas_transport  grocery_net  grocery_pos  \
0              0            0              0            0            0   
1              0            0              0            0            0   
2              0            0              0            0            0   
3              0            0              0            0            0   
4              0            0              0            0            0   

   health_fitness  home  kids_pets  misc_net  misc_pos  personal_care  \
0               0     0          0         0         0              1   
1               0     0          0         0         0              1   
2               1     0          0         0         0              0   
3               0     0          0         0         1              0   
4               0     0          0         0         0              0   

   shopping_net  shopping_pos  travel    amt  city_pop  time_var  
0             0             0       0   2.86    333497         0  
1             0             0       0  29.84       302         0  
2             0             0       0  41.28     34496         0  
3             0             0       0  60.05     54767         0  
4             0             0       1   3.19      1126         0

In [23]:
df_select.describe()

amt      city_pop       is_fraud  time_var_before  \
count  555719.000000  5.557190e+05  555719.000000     5.557190e+05   
mean       69.392810  8.822189e+04       0.003860     2.020097e+13   
std       156.745941  3.003909e+05       0.062008     1.970897e+08   
min         1.000000  2.300000e+01       0.000000     2.020062e+13   
25%         9.630000  7.410000e+02       0.000000     2.020081e+13   
50%        47.290000  2.408000e+03       0.000000     2.020100e+13   
75%        83.010000  1.968500e+04       0.000000     2.020120e+13   
max     22768.110000  2.906700e+06       1.000000     2.020123e+13   

            time_var  
count  555719.000000  
mean        0.945912  
std         0.226192  
min         0.000000  
25%         1.000000  
50%         1.000000  
75%         1.000000  
max         1.000000

# 4.) Oversample the data (this will be your training data).

In [24]:
# do not do

# 5.) Train a Logistic regression.

In [25]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve

In [26]:
log_reg = LogisticRegression().fit(X,y)

In [27]:
log_reg.intercept_

array([-3.03600234])

In [28]:
#log_reg.coef_

# 6.) The company you are working for wants to target at a False Positive rate of 5% what threshold should you use? (Use oversampled data)

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2, random_state = 42)


In [30]:
clf = LogisticRegression()
clf.fit(X_train, y_train)

clf.predict_proba(X_test)

array([[0.99820003, 0.00179997],
       [0.99751196, 0.00248804],
       [0.99777808, 0.00222192],
       ...,
       [0.99646418, 0.00353582],
       [0.99802912, 0.00197088],
       [0.99743401, 0.00256599]])

In [60]:
y_pred =clf.predict(X_test)

fpr, tpr, thresholds = roc_curve(y_test, y_pred)

y_pred_new = np.where(clf.predict_proba(X_test)[:,1] > .006, 1, 0)

confusion_matrix_1 = confusion_matrix(y_test, y_pred_new)

print(confusion_matrix_1)




[[32071 78647]
 [  103   323]]


In [32]:
#confusion_matrix(y_test, y_pred)

# 7.) If the company makes .02*amt on True transactions and loses -amt on False (Use original data)

In [33]:
TP = confusion_matrix_1[0][0]
FP = confusion_matrix_1[0][1]
FN = confusion_matrix_1[1][0]
TN = confusion_matrix_1[1][1]

In [34]:
FN

182

In [37]:
log_reg.predict(X)

array([0, 0, 0, ..., 0, 0, 0])

In [39]:
df_select_temp = df_select.copy()

In [40]:
df_select_temp["pred"] = log_reg.predict(X)

In [41]:
df_select_temp = df_select_temp[["pred","is_fraud","amt"]]

In [44]:
df_select_temp['factor'] = np.where(df_select_temp['pred'] == df_select_temp['is_fraud'], 0.02, -1)

#if the company makes 2% * AMT on TRUE represents the 0.02 here

In [45]:
df_select_temp['profit'] = df_select_temp["amt"]*df_select_temp["factor"]

In [46]:
df_select_temp.head()

pred  is_fraud    amt  factor  profit
0     0         0   2.86    0.02  0.0572
1     0         0  29.84    0.02  0.5968
2     0         0  41.28    0.02  0.8256
3     0         0  60.05    0.02  1.2010
4     0         0   3.19    0.02  0.0638

In [48]:
Final_Profit = sum(df_select_temp["profit"])
Final_Profit

-1235799.7321999532

In [49]:
#x1 * sum(TP) + x2 * sum(FP) + x3 * sum(FN) + x4 *sum(TN)

# 8.) Using Logistic Regression Lasso to inform you. Would you use the selected features in a trusted prediction model?

In [50]:
clf = LogisticRegression(penalty ='l1', solver = 'saga')
clf.fit(X_train, y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_sag.py:352: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


LogisticRegression(penalty='l1', solver='saga')

In [61]:
clf.predict_proba(X_test)

y_probs =clf.predict_proba(X_test)

fpr, tpr, thresholds = roc_curve(y_test, y_probs[:,1])

thresholds_ind = np.abs(fpr - 0.05).argmin()
threshold = thresholds[thresholds_ind]
threshold

0.4823738032074504

In [63]:
_

y_preds = (y_probs[:,1] > threshold).astype(int)

confusion_matrix_2 = confusion_matrix(y_test, y_preds)

print(confusion_matrix_2)


[[105180   5538]
 [   423      3]]


In [ ]:
#see if the variables all go to 0 --> model is terrible , input data is terrible